Add helper class for Snakemake files
ImperialCollegeLondon/virtual_rainforest_snakemake_template pull request #4
Opened 2023-08-17 14:48 UTC by alexdewar

Closes https://github.com/ImperialCollegeLondon/virtual_rainforest/issues/282.

2023-08-21 13:51 UTC, jacobcook1995 approved these changes
It seems like a sensible approach to me, though I must admit I got a bit lost on the details (I think primarily because I'm not familiar with how `snakemake` works).

2023-08-22 08:44 UTC, vgro reviewed
It's the same for me, it looks sensible but I have never used snakemake. I guess it would be useful for us to try and use it with help of your documentation, would that already make sense?

2023-09-11 10:57 UTC, alexdewar commented
@dalonsoa I've belatedly tagged you as a reviewer in case you want to take a look at this. (When I opened the PR originally you were away).

There's no particular rush to merge this, so feel free to leave it until you get a chance, or if you don't have time, let me know and I'll merge it as is.

2023-09-13 05:25 UTC, dalonsoa requested changes
I've made some suggestions, but it looks good to me.

2023-09-13 05:25 UTC, dalonsoa commented on snakemake_helper/parameter_grid.py
> +    def __getitem__(self, ind):
While I see that this will make the whole thing more memory efficient, in terms of code, it is rather convoluted. I wonder if it would be simpler to just store the whole sequence of parameters as an attribute in `__init__` and just access the relevant element when needed. In other words, create the whole sequence by expanding the subgrids and storing the result as a list of parameters. Something like:

```python
# in self.__init__
self.params = []
for p in self.param_grid:
    # Always sort the keys of a dictionary, for reproducibility
    items = sorted(p.items())
    if not items:
        continue

    keys, values = zip(*items)
    for v in product(*values):
        params = dict(zip(keys, v))
        self.params.append(params)
```
You can even make this class a subclass of `list`, replacing the last line with `self.append(params)` and saving the need of implementing `__iter__` and `__getitem__`. 

Unless the number of cases becomes something insane, I'm not sure there is that much to save with this approach.

2023-09-13 11:11 UTC, alexdewar commented on .github/workflows/ci.yml
> +      run: poetry run snakemake --cores all
> If you want to run the workflow even if the test fail, just run this step before the testing step.

Yep, this is what I'm trying to do. The thing is though that I want to run this step as a separate test (to check that running snakemake with the default config works), so I want both of the steps to run, even when one of them fails.

2023-09-13 11:16 UTC, alexdewar commented on README.md
> +```
Hmm... I just tried this and it turns out you can drop the `rule all` in this case. I'll
update the text.

The weird bit about snakemake is that you need to expand the wildcards in your filenames
if you have them and have a rule depend on the explicit filenames. This is kind of
obscured here because it's hidden behind the helper code, but it's why the `input` to
this rule is `exp.all_outputs` rather than `exp.outputs` as we use below. This part of
Snakemake was pretty counterintuitive to me 😅

2023-09-13 11:16 UTC, alexdewar commented on README.md
> +        "analysis_output.toml",
Yep.

2023-09-13 13:39 UTC, dalonsoa approved these changes
Much better :) . All good!

2023-09-13 13:52 UTC, alexdewar commented
Thanks for review :smile:

2023-09-13 14:00 UTC, merged